# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language: python
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      -   id: mypy